### ISSUE TITLE
Duplicated Typescript helpers in output

### ISSUE THREAD

**Issue by impworks** [forCrowd/Labs-Angular-AOTConfiguration#1]
Hello!

When compiling with `tsconfig-compile-aot.json`, each file which contains a class that inherits from some other class gets the `__extends` helper emitted at the beginning of it. As a result, the compiled `app.js` contains multiple copies of the `__extends` helper generated by Typescript - in this example, there are over 50 of them! Rollup doesn't remove this code, but instead gives each instance a unique name.

Is there a way to remove this duplication? When using `await`, the header becomes much bigger and file size becomes an issue.

**Comment by impworks** [comment]
I figured it out. You just need to add the following line to `tsconfig-compile-aot.json`:

```
"importHelpers": true
```

Here's a good article about this compiler flag:
https://blog.mariusschulz.com/2016/12/16/typescript-2-1-external-helpers-library

**Comment by coni2k** [comment]
@impworks Thanks for this catch, very useful info for optimizing the bundle.

However, I read the article, installed "tslib", added "importHelpers" line into all tsconfig files, but I still have 50+ extends in "app.js". Not sure what am I missing.

**Comment by impworks** [comment]
Everything seems correct to me. Try cleaning temporary javascript files generated by `tsconfig-compile-aot.json` - I have a build step that removes them automatically. Maybe they got somehow cached in your case?

**Comment by coni2k** [comment]
I cleaned all generated files/folders but still no luck. Later on I will look into it one more time.
